# Generated by Django 4.2.1 on 2023-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_execution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
