# Generated by Django 4.2.1 on 2023-05-20 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_crawledpage_title_alter_websiterecord_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterecord',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
