# Generated by Django 4.2.1 on 2023-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_websiterecord_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiterecord',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
