# Generated by Django 4.2.1 on 2023-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_crawledpage_title_alter_websiterecord_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='url',
            field=models.URLField(),
        ),
    ]
