# Generated by Django 4.2.1 on 2023-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_crawledpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
