# Generated by Django 4.2.1 on 2023-05-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_crawledpage_id_alter_execution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='execution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
