# Generated by Django 4.2.1 on 2023-05-22 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_crawledpage_url_alter_websiterecord_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='websiterecord',
            name='boundary_regexp',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='websiterecord',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='websiterecord',
            name='periodicity',
            field=models.TextField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], max_length=10),
        ),
        migrations.AlterField(
            model_name='websiterecord',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, size=None),
        ),
    ]
