# Generated by Django 4.2.1 on 2023-05-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_crawledpage_title_alter_crawledpage_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawledpage',
            name='links',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='api.crawledpage')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='api.crawledpage')),
            ],
        ),
    ]
