# Generated by Django 4.2.1 on 2023-05-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_crawledpage_links_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websiterecord",
            name="url",
            field=models.TextField(
                error_messages={
                    "unique": "This URL is already in use. Please use another URL."
                },
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="link",
            unique_together={("from_page", "to_page")},
        ),
    ]
