# Generated by Django 4.0.5 on 2022-06-28 12:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledWeb',
            fields=[
                ('crawledId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('crawlTime', models.FloatField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteRecord',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('regex', models.CharField(blank=True, max_length=265)),
                ('periodicity', models.PositiveIntegerField(help_text='enter time periodicity in seconds (minimal 60 s = 1 min)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(31536000)])),
                ('label', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, help_text='tags must be separeted by ; and space, example: tag1; tag2')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.websiterecord')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkId', models.AutoField(primary_key=True, serialize=False)),
                ('externalUrl', models.URLField()),
                ('crawledId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.crawledweb')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('executionId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('label', models.TextField(max_length=1024)),
                ('executionStartTime', models.DateTimeField(default=datetime.datetime.now)),
                ('executionEndTime', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.BooleanField(default=False)),
                ('sitesCrawled', models.IntegerField(default=0)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.websiterecord')),
            ],
        ),
        migrations.AddField(
            model_name='crawledweb',
            name='recordId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrawler.websiterecord'),
        ),
    ]
